### ISSUE TITLE
Infografia Fases del ciclo de vida del desarrollo de software

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-1-infografia-saul19bautista#2]
[Saul_Infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-saul19bautista/files/12491823/Saul_Infografia.pdf)

**Comment by Edwin14459** [comment]
Redacción y ortografía: No hay faltas de ortografía ni errores gramaticales: 3 puntos
Exposición de ideas centrales: La infografía muestra lo indispensable: 3 puntos
Organización de la información: Establece de manera organizada y creativa la infografía: 3 puntos
Uso de imágenes y colores: La infografía es entendible muy clara y precisa: 3 puntos
Presentación visual: La infografía contiene un buen diseño estructurado: 3 puntos
Referencias: No empleo alguna referencia 0 punto de 2 puntos
Presentación: 3 puntos 
Calificación: 18 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
